const STATUS_CODE = {
    RESOURCE_CREATED: 201,
    RESOURCE_FETCHED: 200,
    RESOURCE_UPDATED: 200,
    RESOURCE_DELETED: 200,
    RESOURCE_NOT_FOUND: 404,
    RESOURCE_ALREADY_EXISTS: 409,
    RESOURCE_FORBIDDEN: 403,
    RESOURCE_UNAUTHORIZED: 401,
    BAD_REQUEST: 400,
    INTERNAL_SERVER_ERROR: 500, 
};

export {
    STATUS_CODE,
}